[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "441e0f7bcc4a804ff384d836bc1adf649693fe49"
libgfortran_version = "5.0.0"
os = "macos"

    [[FMM2D.download]]
    sha256 = "e71689afc271f53ff129416d9ff8f6053b6c17b3374a1c236e831585018ce4ae"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "f13d7f0a938e67b5008ba43fe7a352d953a13771"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "dff4efe62317a2ef8a382e63647762cb49aee946a6b0251ac45fdb895ae3f52f"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "977dffa520c28997eea5ca3745b4e4839449bf3b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "2b3bcf5d736be23f2f4fb8feb34e94cea2500879b6005048d9ddf4fbcd21ed97"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "c78d998bb0b092a9d5a086a16d8bc2b6bc0a6405"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "c70d6873aa88e5164adee0971e7a6a63e64dff31adab1e4f1beb887e6b58dba6"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "8c35186330c699b880d27e32795f17ffe637d2d8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "881fc5db626344e82ffc844d2058cc6460137143ea66f686361f3237e5ef53a6"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "97357a866d75488d3420dcf9f0f627a118d79fcc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "52b7f8fc2d6dff9bb64daeb319f32f3c3441e4a005749e515a998b53cd279e0d"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[FMM2D]]
arch = "aarch64"
git-tree-sha1 = "e7700975cc0e2ad955a5286c583a73303bcd3587"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "d4e780c49f18a74c38904f5d147619610e9845d5fce608e0751200c76b63dd67"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6df7152713c2f341d0200ed3a6f4e61b325d446"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "adfe2d82960ffb3374d3b1d5a7a188182594b864e182cc2e642461c7f19258d3"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "753ed361358557125bfcf0e82b05032bc7d49573"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "445f822815776643f56f4b139f820ee9ba867c6d2cb8a9171c4454553b701b21"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e8a886364d2884cf7a1c4f47dc369d5ccca46e8b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "6d1b205ffcbc3b6c0f9f42cf63e51d64b9f8ae25724e804ecc4aa97dd5f9da20"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cbe791ac5b28a44da9b78b1393eab10c204e86ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "debcd89f0f80fdb00ca85e6d27e6426590a286111bb18ce33f1e56f11e2dd4d2"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "799162f12065eeeece5770a5a105b40b870d3e87"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "8c07bc98d7664b34ec35f30678f9d5e9e7f5e1a5a6762190f839249b2d324955"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[FMM2D]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0826de98539246357bd21df9be8f9a8ea36fa85"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "e255984bbe87bb96c080cd72dfe5111fe8b9f42c167e7a0106b22e6cf4a97f73"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2afbc8b4f9297f75bc27d777adcb372909b3ce1b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "684de037a887a331c1ea94e07f8eb3652e5eeaf097c7c0597f09279e9e1f31f9"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3a1f35bdcec408f115584b8eba7aba6e395b0646"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "4a7a1b90e13f80fa3760bbfaba555e4b38f8af18b85a4a0a2a92217949e4c759"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0078255f9a7ceb2c73de37f47f0e3db583d5abec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "a3ec3ae84a9ef8817de023ce39be0f3de1bbedcb37b6e109de9bf5b4eb153974"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7787aead7d94cb88b0a255bf991497dd1be01966"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "c0efaad3b94f4e7e31767457f1128a3f6293abbe00c04fefdcdaec465ffbc946"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "344a14c8d904ba1fa8d4b264503a602076a39c0d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "d30f6b211b55873af0aa304871403aac9f68ee359d514d44b8a7313c13dd43df"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[FMM2D]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9dbb079eb8386c6e5e326dab1a86c1a156a53477"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "2a469a4063f9ddd233b699ff78e204b7f0ead326576af64698f072f2daced77b"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "68dc9fb1b3d93bbbcc42e2742c4d09df6f7981b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "4bc615946c4e253a009871594b91c4cae781389dbf69eb43d8c923911465d5f5"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "c6d8b0c5082e0bbd2b963350fca2298fa50a85e3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "31604214667533743dd153ccceb490bd637fbaff55662f899da1fd682776784c"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "7d8a322a78b7eeb6f07c9d0648514709f497395c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "4ef758ea61653e5bea028787ff2f4389a447b520144444963e76b8226ac6183f"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "72cb4edd5a50cd95cdd66acf12e43f85ce1fecec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "cda7a627e9e36978a94f3e4311269f5e852e6a1f174e656765e4541ddb9c338d"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-musl-libgfortran3.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "81ada06a6b8e630923915e55e3a83bf311f174b4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "8ffdd9448c13c8c01dcea9582a4da2a248415f2ffeaac48bd0838984411a4340"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-musl-libgfortran4.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "319126907fca4db4adb642bfef7b4abf2845d770"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "e489b2671678e4ee9c8b33b357dde058650874307c8fc1441a00db779f146233"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-linux-musl-libgfortran5.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "4de04697cb362aa3b6487ea09524090e986265eb"
libgfortran_version = "3.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "06b2d1e59655d6d3483409d3a6772bd3a96c4a73d11a72a035fb002448af6526"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "27c9b866fc2f53d127631e730f0083eb92857607"
libgfortran_version = "4.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "bf5a7b946254dda4cc64888d774c2dd70395988d04776bddb7d60a8efbe61b7a"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[FMM2D]]
arch = "i686"
git-tree-sha1 = "66f8cc5b78262c4e4e34f28816d58438feadb82f"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "d8124331714ae35c1488a53ad308427339a3253cce15445191b91758d52f3cb0"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[FMM2D]]
arch = "powerpc64le"
git-tree-sha1 = "b177c29e1c248d674f716cdedde89bfa9f9e0819"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "9bb1761d0af81b03c4894e3e5cd9bfd3c60103755449464fea84c1ff03a5adb8"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[FMM2D]]
arch = "powerpc64le"
git-tree-sha1 = "81aa6d2f09f78ec06690860a876e53d857af536b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "3b814a8b4cf5b4fe0a2ae1c7f2861ca0290ad4d74887353e58df1e9ab71b8cc6"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[FMM2D]]
arch = "powerpc64le"
git-tree-sha1 = "6f45e8c5d59eb96b6762e47acb20169e1d818d0a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "e67e466008b728ce007ad5417745f9dea8847ba1f665c2507fd3b8d556f93327"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "435b261a3aa045cd87c22cf06cf4225b1279526e"
libgfortran_version = "3.0.0"
os = "macos"

    [[FMM2D.download]]
    sha256 = "9dc8d8b8b7ae7e76d8ceeece47af8096ca303689daa7a9f055ef8f532d18da49"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "b7d6f2cfed949252a98e3e5a401a3e7680fd3bec"
libgfortran_version = "4.0.0"
os = "macos"

    [[FMM2D.download]]
    sha256 = "1164ac9017a84b80c777ce44e0e800f41397877506aa82ce6678aa65d95db6e2"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "7f7cad49fac699117f10bc084560865bb8ae1350"
libgfortran_version = "5.0.0"
os = "macos"

    [[FMM2D.download]]
    sha256 = "11d0720cc1ebd5f3943d2fc2b3fef4781c3f5a7f2da0400b82446c3dc0ab987f"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "a290ce7ebeef5d65cfaf69e4c060f8e6932fc77c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "829066c41a9d4543d63a3191d58bf19d313015b1dcd4ba2977de0b4b67187a1b"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "8f235efe81fb0819920a76e0e7a4093ed382e807"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "506ca96a524bb4b340a85a07701ccd58b75654f81e73e3d505fc83902054f336"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "a251ddf099f4d329f4d39c3983f893e8c75d7024"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "5de8da8c4b85797059c3b17c72ba6bcf341896a99010d76d51f1a83ab3755cf8"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "0990649ef2a39a427b297006a7fc99dfba3d0d11"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "77f13a45dd9022ee6729f2abb6b2bd742e08299b9824b10b7673dda5f4cd83a1"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "13b84834262124c1eaf2e5be19ed8af8e55b28b6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "ccaa13f9fad1cde330a32decbd6da93d95c724174a6d8fb82c0e6940903da88b"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "3f540bb72b755429c241a9abee9fd06f15b69f09"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FMM2D.download]]
    sha256 = "62007a1bcf6aa9a0bc412ec864dafe4ae4aa1039bbb2c0a083c22ed501028b94"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "a97f6c5590839d65526652e1b41aa1020eac462f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FMM2D.download]]
    sha256 = "6801e6c33200a21f17ccc0aed52a8b2149f7c61c5c09aff8a5a4a2b5ea4c7ee5"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "c769bd240b7912e35c10c0bd865ba9d879459a81"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FMM2D.download]]
    sha256 = "ba9947db2f54ee92deec2328580585edb5ecf6c1eda6d4232ee3812eb74d4973"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "2d6e091950d80c02197bf773877b5d29ca241a96"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FMM2D.download]]
    sha256 = "5d40cba412e8ec7a4ba04df30a7e254c9a576e1f1731eb6c5ed48ff88bcb10c7"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "ef294a334d417ce42aaf58ac34aa51d92fe3909b"
libgfortran_version = "3.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "faba960984d983ff409c7e482f002d0b376641d197f6514e0634665eb5fa1377"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "2cc6cac0e22acc6538198fff6361b6964be19094"
libgfortran_version = "4.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "8e3855a72080ef0be3a4439df30ac3a2aa292e769e5cd1dad3d7f4c12fa54516"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FMM2D]]
arch = "x86_64"
git-tree-sha1 = "03936648d6b6b5f1d02c7155c8ffb598a6a15456"
libgfortran_version = "5.0.0"
os = "windows"

    [[FMM2D.download]]
    sha256 = "072251dca309be2d546dc0a35f255e9ee5802b2d077aa0410902e92aae242905"
    url = "https://github.com/JuliaBinaryWrappers/FMM2D_jll.jl/releases/download/FMM2D-v1.1.0+0/FMM2D.v1.1.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
