# Autogenerated wrapper script for FMM2D_jll for x86_64-apple-darwin-libgfortran3
export libfmm2d

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("FMM2D")
JLLWrappers.@declare_library_product(libfmm2d, "@rpath/libfmm2d.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libfmm2d,
        "lib/libfmm2d.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
